apiVersion: "xgboostjob.kubeflow.org/v1alpha1"
kind: "XGBoostJob"
metadata:
  name: "xgboost-dist-iris-test-train"
spec:
  xgbReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: lightgbmjob
            image: ubuntu:latest
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            imagePullPolicy: Always
            # args:
            #   - --job_type=Train
            #   - --boosting_type=gbdt
            #   - --objective=binary
            #   - --metric=bnary_logloss,auc
            #   - --metric_freq=1
            #   - --is_training_metric=true
            #   - --max_bin=255
            #   - --data=data/binary.train
            #   - --valid_data=data/binary.test
            #   - --num_trees=100
            #   - --learning_rate=01
            #   - --num_leaves=63
            #   - --tree_learner=feature
            #   - --feature_fraction=08
            #   - --bagging_freq=5
            #   - --bagging_fraction=08
            #   - --min_data_in_leaf=50
            #   - --min_sum_hessian_in_leaf=50
            #   - --is_enable_sparse=true
            #   - --use_two_round_loading=false
            #   - --is_save_binary_file=false
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do echo \"`env`\"; sleep 30; done;" ]
            #command: [ "sleep" ]
            #iargs: [ "infinity" ]
    Worker:
      replicas: 2
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: lightgbmjob
            image: ubuntu:latest
            ports:
            - containerPort: 9991
              name: xgboostjob-port
            # args:
            #   - --job_type=Train
            #   - --boosting_type=gbdt
            #   - --objective=binary
            #   - --metric=bnary_logloss,auc
            #   - --metric_freq=1
            #   - --is_training_metric=true
            #   - --max_bin=255
            #   - --data=data/binary.train
            #   - --valid_data=data/binary.test
            #   - --num_trees=100
            #   - --learning_rate=01
            #   - --num_leaves=63
            #   - --tree_learner=feature
            #   - --feature_fraction=08
            #   - --bagging_freq=5
            #   - --bagging_fraction=08
            #   - --min_data_in_leaf=50
            #   - --min_sum_hessian_in_leaf=50
            #   - --is_enable_sparse=true
            #   - --use_two_round_loading=false
            #   - --is_save_binary_file=false
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "while true; do echo \"`env`\"; sleep 30; done;" ]

